api_platform:
    title: 'Flight Booking API'
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform/resources.yaml']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
