App\Entity\Airport:
    attributes:
        id:
            groups: [ 'read', 'write' ]
        country:
            groups: [ 'read', 'write' ]
        name:
            groups: [ 'read', 'write' ]
        latitude:
            groups: [ 'read', 'write' ]
        longitude:
            groups: [ 'read', 'write' ]