App\Entity\Airport:
    attributes:
        id:
            groups: [ 'flight-read', 'reservation-read' ]
        country:
            groups: [ 'flight-read', 'reservation-read' ]
        name:
            groups: [ 'flight-read', 'reservation-read' ]
        latitude:
            groups: [ 'flight-read', 'reservation-read' ]
        longitude:
            groups: [ 'flight-read', 'reservation-read' ]