App\Entity\Flight:
    attributes:
        id:
            groups: [ 'flight-read', 'reservation-read' ]
        departureAirport:
            groups: [ 'flight-read', 'reservation-read' ]
        arrivalAirport:
            groups: [ 'flight-read', 'reservation-read' ]
        plane:
            groups: [ 'flight-read', 'reservation-read' ]
        departureDatetime:
            groups: [ 'flight-read', 'reservation-read' ]