App\Entity\Plane:
    attributes:
        id:
            groups: [ 'flight-read', 'reservation-read' ]
        name:
            groups: [ 'flight-read', 'reservation-read' ]
        seats:
            groups: [ 'flight-read' ]