reservation_create:
    path: /api/reservations
    controller: App\Controller\ReservationController::create
    methods: POST

reservation_update:
    path: /api/reservations
    controller: App\Controller\ReservationController::patch
    methods: PATCH

login:
    path: /api/login
    methods: POST

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
