App\Entity\Reservation:
    collectionOperations:
        get: ~
    itemOperations:
        get: ~
        delete: ~
    attributes:
        normalization_context:
            groups: [ 'reservation-read' ]
        denormalization_context:
            groups: [ 'write' ]