App\Entity\Airport:
    type: entity
    repositoryClass: App\Repository\AirportRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        country:
            type: string
            length: 255
            nullable: false
        name:
            type: string
            length: 255
            nullable: false
        latitude:
            type: float
            nullable: false
        longitude:
            type: float
            nullable: false
    oneToMany:
        departureFlights:
            targetEntity: App\Entity\Flight
            mappedBy: departureAirport
        arrivalFlights:
            targetEntity: App\Entity\Flight
            mappedBy: arrivalAirport