App\Entity\Flight:
    type: entity
    repositoryClass: App\Repository\FlightRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        departureDatetime:
            type: datetime
            nullable: false
    manyToOne:
        departureAirport:
            inversedBy: departureFlights
            targetEntity: App\Entity\Airport
            joinColumn:
                name: departure_airport_id
                referencedColumnName: id
                nullable: false
        arrivalAirport:
            inversedBy: arrivalFlights
            targetEntity: App\Entity\Airport
            joinColumn:
                name: arrival_airport_id
                referencedColumnName: id
                nullable: false
        plane:
            inversedBy: flights
            targetEntity: App\Entity\Plane
            joinColumn:
                nullable: false
    oneToMany:
        reservations:
            mappedBy: flight
            targetEntity: App\Entity\Reservation