App\Entity\Reservation:
    type: entity
    repositoryClass: App\Repository\ReservationRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        departureDatetime:
            type: datetime
            nullable: false
    manyToOne:
        departureAirport:
            inversedBy: departureReservations
            targetEntity: App\Entity\Airport
            joinColumn:
                name: departure_airport_id
                referencedColumnName: id
                nullable: false
        arrivalAirport:
            inversedBy: arrivalReservations
            targetEntity: App\Entity\Airport
            joinColumn:
                name: arrival_airport_id
                referencedColumnName: id
                nullable: false
