App\Entity\Reservation:
    type: entity
    repositoryClass: App\Repository\ReservationRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        user:
            type: string
            nullable: false
        datetime:
            type: datetime
            nullable: false
        status:
            type: string
            nullable: false
    manyToOne:
        flight:
            inversedBy: reservations
            targetEntity: App\Entity\Flight
            joinColumn:
                nullable: false
        seat:
            inversedBy: reservations
            targetEntity: App\Entity\Seat
            joinColumn:
                nullable: false