App\Entity\User:
  type: entity
  repositoryClass: App\Repository\UserRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    email:
      type: string
    password:
      type: string
    firstname:
      type: string
    lastname:
      type: string
    roles:
      type: string
      nullable: true